name: Build
on: [push]
jobs:
  Build:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Build page
        uses: actions-rs/install@v0.1
        with: 
          crate: mdbook
          version: latest
      - run: mdbook build
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4